apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: dev
  labels: 
    app: jenkins
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: abdelrahman1111/docker-jenkins:docker-jenkins-kubectl
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-volume
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName:  pvc-jenkins