apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: dev
  labels: 
    app: jenkins
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: cluster-admin
      containers:
      - name: jenkins
        image: abdelrahman1111/docker-jenkins:docker-jenkins-kubectl
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-volume
        - mountPath: /var/run/docker.sock
          name: docker-daemon-volume
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
          claimName:  pvc-jenkins
        - name: docker-daemon-volume
          hostPath: 
            path: /var/run/docker.sock 
