apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: dev
  annotations:
        cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080