apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-jenkins
    namespace: dev
spec:
    storageClassName: "jenins-disk" 
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi